version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: esthomy_db
      POSTGRES_USER: esthomyuser
      POSTGRES_PASSWORD: esthomy2000*
    ports:
      - "5432:5432"

  services:
    image: esthomy-backend
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/esthomy_db
      SPRING_DATASOURCE_USERNAME: esthomyuser
      SPRING_DATASOURCE_PASSWORD: esthomy2000*
    depends_on:
      - postgres
