server:
    port: 8080

jwt:
  access:
    expiration: 5m
    secret:
      key: 06012000!-06042000?*-2404-2000*&
  refresh:
    expiration: 10m
    secret:
      key: 06012000!-06042000?*-2404-2000*&
    issuer: aesthetics


spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:TestEsthomy
    username: sa
    password: 123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

cookie:
  accessTokenCookieName: ACCESS_TOKEN
  refreshTokenCookieName: REFRESH_TOKEN
